// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ9614FlgXORGRmLFtm5uBV0q3YcNKTQw',
    appId: '1:84362351090:web:33b0ae63d3ed784789db6b',
    messagingSenderId: '84362351090',
    projectId: 'lionsbotremotecontroller',
    authDomain: 'lionsbotremotecontroller.firebaseapp.com',
    storageBucket: 'lionsbotremotecontroller.appspot.com',
    measurementId: 'G-RRPEVNXKD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAizyX6HX8TEy1FKEI_xnzlxsa-2k7eBFU',
    appId: '1:84362351090:android:d89ac584ce1ec29c89db6b',
    messagingSenderId: '84362351090',
    projectId: 'lionsbotremotecontroller',
    storageBucket: 'lionsbotremotecontroller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn23IlzuQsjenlqTl1qD94V2Dsu3t7Wuc',
    appId: '1:84362351090:ios:c174d3669ba95d7e89db6b',
    messagingSenderId: '84362351090',
    projectId: 'lionsbotremotecontroller',
    storageBucket: 'lionsbotremotecontroller.appspot.com',
    iosBundleId: 'com.example.lionsbotremotecontroller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn23IlzuQsjenlqTl1qD94V2Dsu3t7Wuc',
    appId: '1:84362351090:ios:77eb44f6980a379589db6b',
    messagingSenderId: '84362351090',
    projectId: 'lionsbotremotecontroller',
    storageBucket: 'lionsbotremotecontroller.appspot.com',
    iosBundleId: 'com.example.lionsbotremotecontroller.RunnerTests',
  );
}
